[package]
version = "1.0.1"
category = "Simulation"
title = "MTConnect Stream"
description = "Stream MTConnect data from an MTConnect Agent"
authors = ["Proces Robotics"]
repository = ""
keywords = ["mtconnect", "streaming", "manufacturing"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.gui.components" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "isaacsim_mtconnect_stream_python"

[[ogn]]
path = "ogn"

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]
